name: Pull-Requests Check

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - scott/unittests
  pull_request:
    branches:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          bundler-cache: true

      - name: Setup venv
        run: python3 -m venv venv

      - name: Build and test with pytest
        run: source venv/bin/activate && pytest tests/
